### ISSUE TITLE
ERROR 1.16.3

### ISSUE THREAD

**Issue by dinobossytnew** [KyosaiTech/SupplyDrop#2]
https://pastebin.com/p3TgtXHR

**Comment by KyosaiTech** [comment]
https://www.mediafire.com/file/c1get0mj7udg7z5/SupplyDrop-1.0.2-SNAPSHOT-API1.15.2-all.jar/file

**Comment by KyosaiTech** [comment]
https://discord.gg/wwgbwDZmjU
